providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd website-next && npm ci"]

[phases.build]
cmds = ["cd website-next && npm run build"]

[start]
cmd = "cd website-next && npm run start"
